- docs/deployment/configuration/files.md
closes https://github.com/onepanelio/manifests/pull/49
> Adding documentation for node selector and auto scaling options.

- docs/api-sdk/overview.md
- docs/deployment/configuration/cli.md
- docs/deployment/configuration/files.md
- docs/deployment/configuration/tls.md
- docs/deployment/overview.md
- docs/deployment/public/aks.md
- docs/deployment/public/eks.md
- docs/deployment/public/gke.md
- docs/deployment/single-node/microk8s.md
- docs/deployment/single-node/minikube.md
- docs/deployment/troubleshooting/overview.md
- docs/deployment/upgrade/overview.md
- docs/getting-started/concepts/environment-variables.md
- docs/getting-started/concepts/namespaces.md
- docs/getting-started/concepts/workflows.md
- docs/getting-started/concepts/workspaces.md
- docs/getting-started/contributing.md
- docs/getting-started/quickstart.md
- docs/getting-started/use-cases/computervision/annotation/cvat/cvat_annotation_model.md
- docs/getting-started/use-cases/computervision/annotation/cvat/cvat_automatic_annotation.md
- docs/getting-started/use-cases/computervision/annotation/cvat/cvat_quick_guide.md
- docs/reference/overview.md
- docs/reference/workflows/templates.md
- docs/reference/workspaces/delete.md
- docs/reference/workspaces/launching.md
- docs/reference/workspaces/pause-and-resume.md
- docs/reference/workspaces/templates.md
- docs/reference/workspaces/upgrade.md
- src/pages/index.js
Adds better SEO elements to docs
> docs: Update SEO

- docs/getting-started/use-cases/computervision/annotation/cvat/cvat_quick_guide.md
* Updates the default cvat credentials in the documentation
> docs: update cvat_quick_guide.md

- docs/deployment/configuration/cli.md
- docs/deployment/configuration/files.md
- docs/reference/workflows/templates.md
Adds documentation for `--artifact-repository-provider` flag.
Fixes onepanelio/core#331
> feat: core.331-support.gcs.artifact

- docs/reference/workflows/templates.md
> docs: added faqs for workflows

- docs/reference/services/modeldb.md
> feat: added documentation for modeldb's s3 bucket CORS

- docs/deployment/configuration/files.md
- docs/reference/workspaces/templates.md
> feat: Adding extra information about minikube and nodepool labels. Added setup steps regarding workspaces and DNS on minikube.

- docs/getting-started/use-cases/computervision/annotation/cvat/adding_custom_model.md
- docs/getting-started/use-cases/computervision/annotation/cvat/cvat_annotation_model.md
- docs/getting-started/use-cases/computervision/annotation/cvat/cvat_quick_guide.md
> docs: corrected listing on adding custom model page

- docusaurus.config.js
> docs: Update top menu item title

- docs/reference/workflows/templates.md
Adds the information about the visibility of parameters
> docs: add information about visibility of parameters

- docs/deployment/configuration/files.md
Our code will figure out the proper resources to request.
- And we no longer support params.yaml providing the resources.
So this documentation is no longer accurate nor needed.
> feat: Remove the documentation for requesting resources in nodePool

- docs/deployment/public/eks.md
- docs/deployment/public/gke.md
- docs/getting-started/quickstart.md
- src/pages/index.js
Update cloud provider commands
> docs: Update cloud provider commands

- docs/reference/workflows/templates.md
- docs/reference/workspaces/templates.md
> feat: added select.nodepool documentation

- docs/getting-started/quickstart.md
> docs: Update note about eksctl version

- docs/getting-started/contributing.md
- docs/getting-started/quickstart.md
> docs: Minor updates

- docs/getting-started/quickstart.md
getting started youtube video links update
update youtube hyperlink for AKS deployment video guide
> docs: Update getting-started hyperlinks

- docs/getting-started/quickstart.md
updating hyperlinks to point into new deployment videos
> docs: Update getting started video links

- docs/getting-started/quickstart.md
update to initiate gke clusters with gcs
> docs: update gke init command

- docs/deployment/configuration/files.md
update gcs deployment yaml configuration
> docs: update gcs configuration

- docs/reference/workflows/hyperparameter-tuning.md
> feat: Update hyperparameter tuning docs

- docs/getting-started/quickstart.md
> feat: added step to label your nodes in microk8s

- docs/getting-started/quickstart.md
> fix: issue where labeling nodes was being shown for all providers

- docs/getting-started/quickstart.md
> docs: updated tabs in step 6 - status command

- docs/deployment/configuration/remote-microk8s.md
- docs/deployment/configuration/remote_microk8s.md
- docs/getting-started/quickstart.md
- sidebars.js
> feat: added documentation to running microk8s on a remote vm

- docs/deployment/configuration/remote-microk8s.md
added guide on how to properly setup gpu nodes from Microk8s
link guide on how to mount disks in VMs
> docs: enabling GPU nodes with Microk8s

- docs/deployment/configuration/remote-microk8s.md
> docs: updated "note" > "important"

- docs/deployment/configuration/miniotenants.md
- sidebars.js
guide on how to deploy minio tenants with Onepanel
> docs: Guide for deploying MinIO Tenants with Onepanel

- docs/deployment/configuration/remote-microk8s.md
> fix: issue where uploads were limited in size by nginx for remote microk8s 

- package-lock.json
> feat: package updates

- docs/deployment/configuration/miniotenants.md
added guide on how to deploy MinIO operators & tenants with Onepanel
> docs: Microk8s + MinIO Operators

- docs/deployment/configuration/remote-microk8s.md
> docs: added GPU support

- sidebars.js
> fix errors

- docs/reference/cvat/custom-models.md
fixes broken images in /docs/reference/cvat/custom-models#3-update-the-training-code
> fix: broken images

- docs/getting-started/quickstart.md
this version is required so gpu nodegroups can autoscale without errors
provides users information on the current stable version with eksctl for autoscaling gpu nodegroups
> docs: added stable version for eksctl

- docs/deployment/configuration/remote-microk8s.md
> docs: added Provider for gpu example

- docs/deployment/configuration/remote-microk8s.md
> merging both patch branches

- docs/deployment/components/nodes.md
- docs/getting-started/quickstart.md
fixes error with autoscaling nodes for the latest eksctl binaries
> docs: assign unmanaged nodes to eksctl/latest clusters & nodegroups

- docs/reference/cvat/cvat_1_6.md
- sidebars.js
> feat: cvat 1.6.0 docs

- docs/reference/cvat/cvat_1_6.md
> feat: indicate what model is deployed in cvat dos

- src/pages/index.js
> feat: remove enterprise link
